### PR TITLE
Fix Menu Trigger callbacks

### LINKED ISSUE #152: [BUG] Menu Trigger callbacks don't work
onLTrigger and onRTrigger script callbacks are never called when using a controller.

### PR DESCRIPTION
**Pull request by polyrain**
This PR adds handling and debouncing logic for the XInput triggers in the menus. This has been tested locally (by switching the `onLTrigger` to `onA` as well as printing), but if we need to add actual tests just let me know. 

Closes #152

### CODE REVIEW

File: engine/source/gui/core/guiCanvas.cpp [hunk 1]
```diff
@@ -573,14 +573,13 @@ bool GuiCanvas::processInputEvent(const InputEvent* event)
...
         // Do NOT PUT THE gLastEventTime change here, it will pick up the analog stick noise
-
         //copy the modifier into the new event
         mLastEvent.modifier = event->modifier;
-        
         bool retval = false;
 
         if (event->objType == SI_BUTTON || event->objType == SI_POV)
         {
+            Con::printf("Type was SI_BUTTON etc");
```
Comment (HumanGamer) [inline engine/source/gui/core/guiCanvas.cpp]: We shouldn't have print outs in input code, we don't need console spam except for debugging.

File: engine/source/gui/core/guiCanvas.cpp [hunk 2]
```diff
@@ -648,17 +665,27 @@ bool GuiCanvas::processInputEvent(const InputEvent* event)
...
+                else if (event->objType == XI_RIGHT_TRIGGER)
+                {
+                    retval = responder->onGamepadButtonPressed(XI_RIGHT_TRIGGER);  
+                }
                 gLastEventTime = curTime;
             }
 
             return retval;
+        } else {
+            Con::printf("Input fell outside current logic. Maybe theres a bug!");
```
Comment (HumanGamer) [inline engine/source/gui/core/guiCanvas.cpp:691]: If this only occurs when there's an issue, it should use Con::warnf or Con::errorf

**Review by HumanGamer — CHANGES_REQUESTED** [review]
I haven't tested in game yet, but I noticed 2 things I'd like you to adjust in your PR.

File: engine/source/gui/core/guiCanvas.cpp (hunk 1 above)
Comment (polyrain) [reply engine/source/gui/core/guiCanvas.cpp]: Yeah, already spotted and removed! Left it in by mistake

File: engine/source/gui/core/guiCanvas.cpp (hunk 2 above)
Comment (polyrain) [reply engine/source/gui/core/guiCanvas.cpp:691]: Gotcha, I'll update this now.

**Review by HumanGamer — APPROVED** [review]
Looks good to me.
